# -*- coding: utf-8 -*-
{
    'name': 'Field Pass Tracker',
    'version': '16.0.3.0.0',
    'category': 'Human Resources',
    'summary': 'Track employee and vehicle field passes, document expiry and compliance for oilfield operations',
    'author': 'Your Company Name',
    'license': 'OPL-1',
    'depends': ['base', 'hr', 'mail', 'base_setup'],
    'data': [
        'security/field_pass_security.xml',
        'security/ir.model.access.csv',
        'data/field_pass_alert_config_data.xml',
        'data/field_pass_cron.xml',
        'views/hr_department_views.xml',
        'views/field_pass_employee_views.xml',
        'views/field_pass_vehicle_views.xml',
        'views/field_pass_views.xml',
        'views/field_pass_alert_config_views.xml',
        'views/field_pass_dashboard_views.xml',
        'views/field_pass_lang_views.xml',
        'views/field_pass_renewal_views.xml',
        'views/field_pass_wizard_views.xml',
        'views/field_pass_viewer_access.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'translations': ['i18n/ar.po'],
}
